### ISSUE TITLE
VU Issues

### ISSUE THREAD

**Issue by FlashHit** [FlashHit/VU-Issues#1]
Categories:
1. must have (or just easy to fix)
2. very good to have
3. nice to have
4. not that important to have

## Vanilla Relevant issues
- [x] Spawning on squadmates not blocked · [Issue #576](https://github.com/EmulatorNexus/VeniceUnleashed/issues/576) · 1
- [x] Squads not getting assigned properly · [Issue #679](https://github.com/EmulatorNexus/VeniceUnleashed/issues/679) · 2
- [ ] Gunmaster - pickup kit · [Issue #645](https://github.com/EmulatorNexus/VeniceUnleashed/issues/645) · 3

## RM Relevant issues

Requests:
- [x] Prevent player from automatically joining squads when joining US team · [Issue #371](https://github.com/EmulatorNexus/VeniceUnleashed/issues/371) · 2
- [ ] Remove weapon glance / shine · [Issue #447](https://github.com/EmulatorNexus/VeniceUnleashed/issues/447) · 3
- [ ] Add a way to see current memory usage by UI/Lua/Vext · [Issue #693](https://github.com/EmulatorNexus/VeniceUnleashed/issues/693) · 3
- [ ] `ClientUtils:GetFov()` & `ClientUtils:SetFov(float)` · [Issue #511](https://github.com/EmulatorNexus/VeniceUnleashed/issues/511) · 3
- [x] Allow access to first person camera · [Issue #393](https://github.com/EmulatorNexus/VeniceUnleashed/issues/393) · 3
- [x] VU Launch Argument to automatically login to VU account · [Issue #465](https://github.com/EmulatorNexus/VeniceUnleashed/issues/479) · 3
- [ ] VoIP: Add VoIP event for players that enter/leave hearing radius in positional channels · [Issue #710](https://github.com/EmulatorNexus/VeniceUnleashed/issues/710) · 3
- [ ] Allow subscribing to vanilla RCON commands · [Issue #689](https://github.com/EmulatorNexus/VeniceUnleashed/issues/689) · 3
- [ ] Hook or event that triggers on Lua errors · [Issue #664](https://github.com/EmulatorNexus/VeniceUnleashed/issues/664) · 4
- [ ] Discord integration custom map name · [Issue #614](https://github.com/EmulatorNexus/VeniceUnleashed/issues/614) · 4
- [x] Implement weapon changing event · [Issue #465](https://github.com/EmulatorNexus/VeniceUnleashed/issues/465) · 4
- [x] Add event for player leaving combat area boundaries · [Issue #497](https://github.com/EmulatorNexus/VeniceUnleashed/issues/497) · 4
- [x] Add previousSquadId to Player:SquadChange event · [Issue #474](https://github.com/EmulatorNexus/VeniceUnleashed/issues/474) · 4
- [x] Http redirect / alternative mirrors for ui.vuic  · [Issue #711](https://github.com/EmulatorNexus/VeniceUnleashed/issues/711) · 4
- [ ] Make `PhysicsEntity.velocity` writable · [Issue #747](https://github.com/EmulatorNexus/VeniceUnleashed/issues/747) · 4

Bugs:
- [ ] Out of memory / memory leak / memory issues · [Issue #764](https://github.com/EmulatorNexus/VeniceUnleashed/issues/764) · 1
- [x] `Player:SetSquadLeader` event is not working · [Issue #746](https://github.com/EmulatorNexus/VeniceUnleashed/issues/746) · 1
- [x] Error: error in error handling · [Issue #724](https://github.com/EmulatorNexus/VeniceUnleashed/issues/724) · 1
- [ ] Corrupted instances on Partition:Loaded when running custom map + RM · [Issue #633](https://github.com/EmulatorNexus/VeniceUnleashed/issues/633) · 1
- [x] VoIP: Client - Unplugging microphone causes crash · [Issue #705](https://github.com/EmulatorNexus/VeniceUnleashed/issues/705) · 1
- [ ] VU Client crashes when the Windows Audio Output is removed · [Issue #737](https://github.com/EmulatorNexus/VeniceUnleashed/issues/737) · 1
- [ ] Silent crash when changing audio volume in settings · [Issue #751](https://github.com/EmulatorNexus/VeniceUnleashed/issues/751) · 1
- [ ] Silent crash when pressing 'apply' in the VU settings tab in the settings · [Issue #752](https://github.com/EmulatorNexus/VeniceUnleashed/issues/752) · 1
- [x] ModSettings don't update strings & options · [Issue #744](https://github.com/EmulatorNexus/VeniceUnleashed/issues/744) · 2
- [x] `vu.DrawMemoryStats` bugged · [Issue #741](https://github.com/EmulatorNexus/VeniceUnleashed/issues/741) · 2
- [x] `SoldierEntity.weaponsComponent.weapons` changed · [Issue #743](https://github.com/EmulatorNexus/VeniceUnleashed/issues/743) · 2
- [x] `AimingSimulation.zoomLevel` is/gets bugged · [Issue #671](https://github.com/EmulatorNexus/VeniceUnleashed/issues/671) · 3
- [ ] `ConceptCache:SetLevel` not working  · [Issue #681](https://github.com/EmulatorNexus/VeniceUnleashed/issues/681) · 3
- [x] Wrong levelName in `Level:Loaded` event · [Issue #745](https://github.com/EmulatorNexus/VeniceUnleashed/issues/745) · 3
- [ ] VoIP: volume is too low · [Issue #706](https://github.com/EmulatorNexus/VeniceUnleashed/issues/706) · 3
- [x] `Player:UpdateInput` stopped working · [Issue #742](https://github.com/EmulatorNexus/VeniceUnleashed/issues/742) · 3
- [x] Error with no traceback: `RegisterDestroyCallback` wrong · [Issue #445](https://github.com/EmulatorNexus/VeniceUnleashed/issues/445#issuecomment-892270245) · 4
- [x] `VoipEmitter:Emitting` gets triggered twice · [Issue #707](https://github.com/EmulatorNexus/VeniceUnleashed/issues/707) · 4
- [ ] VoIP: Can't remove player from channel after a round restart · [Issue #721](https://github.com/EmulatorNexus/VeniceUnleashed/issues/721) · 4
- [ ] VoIP: Emitting event is not triggered when a player that is transmitting is removed from the channel · [Issue #716](https://github.com/EmulatorNexus/VeniceUnleashed/issues/716) · 4
- [x] ~Research multiple cases of extremely long server connection times · [Issue #753](https://github.com/EmulatorNexus/VeniceUnleashed/issues/753) · 4~

## FunBots Relevant issues

Requests:
- [x] Allow Bots to aim · [Issue #622](https://github.com/EmulatorNexus/VeniceUnleashed/issues/622) · 2
- [x] Server Player method to choose perks · [Issue #620](https://github.com/EmulatorNexus/VeniceUnleashed/issues/620) · 2
- [ ] Add MCOM Events (Planted, Defused, Exploded) · [Issue #498](https://github.com/EmulatorNexus/VeniceUnleashed/issues/498) · 3

Bugs:
- [ ] Server sided weapon animation does not work properly · [Issue #602](https://github.com/EmulatorNexus/VeniceUnleashed/issues/602) · 3
- [ ] Kits missing with high player counts · [Issue #722](https://github.com/EmulatorNexus/VeniceUnleashed/issues/722) · 3
- [x] Client-CollitionRaycast and DetailedRaycast crash the Client if Async · [Issue #715](https://github.com/EmulatorNexus/VeniceUnleashed/issues/715) · 3
- [x] ServersidedRaycasts: latency-Raycasts · [Issue #714](https://github.com/EmulatorNexus/VeniceUnleashed/issues/714) · 3
- [x] Serversided Raycasts: maxHits without function · [Issue #713](https://github.com/EmulatorNexus/VeniceUnleashed/issues/713) · 3
- [x] Server-Raycasts: Materials get ignored · [Issue #709](https://github.com/EmulatorNexus/VeniceUnleashed/issues/709) · 3
- [x] Serversided Async-Raycast crashes · [Issue #708](https://github.com/EmulatorNexus/VeniceUnleashed/issues/708) · 3
- [x] SQL:Open fails · [Issue #678](https://github.com/EmulatorNexus/VeniceUnleashed/issues/678) · 3
- [ ] improve soldier:SingleStepEntry() & EntryInput · [Issue #685](https://github.com/EmulatorNexus/VeniceUnleashed/issues/685) · 4
- [ ] Ingame Console (Client) not working if folder of mod has dots in it's name · [Issue #663](https://github.com/EmulatorNexus/VeniceUnleashed/issues/663) · 4

## BR Relevant issues

Requests:
- [x] Component support · [Issue #669](https://github.com/EmulatorNexus/VeniceUnleashed/issues/669) · 2
- [ ] function to close/ open parachute · [Issue #627](https://github.com/EmulatorNexus/VeniceUnleashed/issues/627) · 2

Bugs:
- [x] `Player:UpdateInput` stopped working · [Issue #742](https://github.com/EmulatorNexus/VeniceUnleashed/issues/742) · 1
- [x] ModSettings don't update strings & options · [Issue #744](https://github.com/EmulatorNexus/VeniceUnleashed/issues/744) · 1
- [x] Error: error in error handling · [Issue #724](https://github.com/EmulatorNexus/VeniceUnleashed/issues/724) · 2
- [ ] `vu://join/<server-guid>[/<password>]` · [Issue #725](https://github.com/EmulatorNexus/VeniceUnleashed/issues/725) · 2
- [ ] Server sided weapon animation does not work properly · [Issue #602](https://github.com/EmulatorNexus/VeniceUnleashed/issues/602) · 4

## Other general issues

Requests:
- [ ] `SharedUtils:GetLevelLoadingInfo()` · [Issue #687](https://github.com/EmulatorNexus/VeniceUnleashed/issues/687) · 1
- [ ] `partition.compartment` · [Issue #718](https://github.com/EmulatorNexus/VeniceUnleashed/issues/718) · 2
- [ ] `mod.version`, `mod.description`, etc. · [Issue #523](https://github.com/EmulatorNexus/VeniceUnleashed/issues/523) · 3
- [x] VU Server Launch argument `-maxPlayers` · [Issue #513](https://github.com/EmulatorNexus/VeniceUnleashed/issues/513) · 3
- [ ] Add MCOM Events (Planted, Defused, Exploded) · [Issue #498](https://github.com/EmulatorNexus/VeniceUnleashed/issues/498) · 3
- [x] `CapturePointEntity:Capture(team TeamId)` · [Issue #487](https://github.com/EmulatorNexus/VeniceUnleashed/issues/487) · 3
- [ ] Cancel button for server loadscreen · [Issue #415](https://github.com/EmulatorNexus/VeniceUnleashed/issues/415) · 3
- [x] ~`SharedUtils:GetBuildId()`  · [Issue #738](https://github.com/EmulatorNexus/VeniceUnleashed/issues/738)  · 3~
- [x] Client/Server `Player.isAllowedToSpawnOn` · [Issue #676](https://github.com/EmulatorNexus/VeniceUnleashed/issues/676) · 4
- [x] Add microseconds version of GetTime · [Issue #736](https://github.com/EmulatorNexus/VeniceUnleashed/issues/736) · 4
- [ ] Allow switching soldier without closing the game · [Issue #666](https://github.com/EmulatorNexus/VeniceUnleashed/issues/666) · 4
- [ ] `PickupEntity` · [Issue #624](https://github.com/EmulatorNexus/VeniceUnleashed/issues/624) · 4
- [x] `ClientSpottingTargetComponent` · [Issue #530](https://github.com/EmulatorNexus/VeniceUnleashed/issues/530) · 4
- [ ] Expose stats to VEXT · [Issue #394](https://github.com/EmulatorNexus/VeniceUnleashed/issues/394) · 4

Bugs:
- [x] `vu.SetTeamTicketCount` doesn't work for `KillCounterEntities` (TDM) · [Issue #729](https://github.com/EmulatorNexus/VeniceUnleashed/issues/729) · 1
- [x] `vu.DestructionEnabled` seems bugged · [Issue #690](https://github.com/EmulatorNexus/VeniceUnleashed/issues/690) · 1
- [x] `modList` - Inconsistent casing · [Issue #508](https://github.com/EmulatorNexus/VeniceUnleashed/issues/508) · 1 (if easy, else 4)
- [x] Using `InputManager:GetMouseLevel` causes a silent CTD · [Issue #608](https://github.com/EmulatorNexus/VeniceUnleashed/issues/608) · 2
- [x] VeniceEXT Arrays Causing Crashes · [Issue #598](https://github.com/EmulatorNexus/VeniceUnleashed/issues/598) · 2
- [x] Using either vu.com or -headless does not prevent the error window from popping up · [Issue #723](https://github.com/EmulatorNexus/VeniceUnleashed/issues/723) · 3
- [x] Client `ControllableEntity:GetPlayerInEntry()` not working · [Issue #702](https://github.com/EmulatorNexus/VeniceUnleashed/issues/702) · 3
- [x] `AimingSimulation.zoomTransitionTime` always `nil` · [Issue #670](https://github.com/EmulatorNexus/VeniceUnleashed/issues/670) · 3
- [x] Crash in `MathUtils:GetYPRFromULF` · [Issue #692](https://github.com/EmulatorNexus/VeniceUnleashed/issues/692) · 3
- [x] Client `RegisterDamageCallback` returns weird `DamageInfo` · [Issue #637](https://github.com/EmulatorNexus/VeniceUnleashed/issues/637) · 3
- [ ] 120hz Grenade trajectory (high freq issue) · [Issue #623](https://github.com/EmulatorNexus/VeniceUnleashed/issues/623) · 3
- [ ] First person model flickers when running in high frequency · [Issue #131](https://github.com/EmulatorNexus/VeniceUnleashed/issues/131) · 3
- [ ] `VoipEmitter.muted` isn't muting the emitter · [Issue #727](https://github.com/EmulatorNexus/VeniceUnleashed/issues/727) · 4
- [x] Crash when printing a class (recursive print) · [Issue #686](https://github.com/EmulatorNexus/VeniceUnleashed/issues/686) · 4
- [ ] using `:Unsubscribe()` twice · [Issue #617](https://github.com/EmulatorNexus/VeniceUnleashed/issues/617) · 4
- [x] `PhysicsEntityBase` property `sleeping` not working properly · [Issue #601](https://github.com/EmulatorNexus/VeniceUnleashed/issues/601) · 4
- [ ] `InputManager` doesn't seem to register events for `InputConceptIdentifiers.ConceptJump` · [Issue #586](https://github.com/EmulatorNexus/VeniceUnleashed/issues/586) · 4
